services:
  postgres:
    image: postgres:16
    container_name: level-up-db
    environment:
      POSTGRES_USER: levelup
      POSTGRES_PASSWORD: levelup
      POSTGRES_DB: levelup
    ports:
      - "5433:5432"
    volumes:
      - level-up-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U levelup"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    container_name: level-up-backend
    environment:
      - DATABASE_URL=postgres://levelup:levelup@postgres:5432/levelup
      - PORT=4000
      - NODE_ENV=development
    ports:
      - "4000:4000"
    volumes:
      - ./packages/backend:/workspace/packages/backend
      - ./tsconfig.json:/workspace/tsconfig.json
      - /workspace/packages/backend/node_modules
    working_dir: /workspace/packages/backend
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health-check"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    command: pnpm start:dev

  drizzle-studio:
    build:
      context: .
      dockerfile: packages/backend/Dockerfile
    container_name: level-up-drizzle-studio
    environment:
      - DATABASE_URL=postgres://levelup:levelup@postgres:5432/levelup
    ports:
      - "4466:4466"
    volumes:
      - ./packages/backend:/workspace/packages/backend
      - ./tsconfig.json:/workspace/tsconfig.json
      - /workspace/packages/backend/node_modules
    working_dir: /workspace/packages/backend
    depends_on:
      postgres:
        condition: service_healthy
    command: pnpm db:studio

  frontend:
    build:
      context: .
      dockerfile: packages/frontend/Dockerfile
    container_name: level-up-frontend
    environment:
      - NODE_ENV=development
    ports:
      - "5173:5173"
    volumes:
      - ./packages/frontend:/workspace/packages/frontend
      - ./tsconfig.json:/workspace/tsconfig.json
      - /workspace/packages/frontend/node_modules
    working_dir: /workspace/packages/frontend
    command: pnpm dev
    depends_on:
      - backend

volumes:
  level-up-data:
