version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: level-up-db
    environment:
      POSTGRES_USER: levelup
      POSTGRES_PASSWORD: levelup
      POSTGRES_DB: levelup
    ports:
      - "5433:5432"
    volumes:
      - level-up-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U levelup"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  level-up-data:
